//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ride_detail
    {
        public int id { get; set; }
        public int passengerID { get; set; }
        public int driverID { get; set; }
        public int from_destination { get; set; }
        public int to_destination { get; set; }
        public Nullable<int> from_lat { get; set; }
        public Nullable<int> from_lng { get; set; }
        public Nullable<int> to_lat { get; set; }
        public Nullable<int> to_lng { get; set; }
        public System.DateTime reserve_date_start { get; set; }
        public System.DateTime reserve_date_end { get; set; }
        public System.DateTime created_date { get; set; }
        public int total_miles { get; set; }
        public double amount { get; set; }
        public string status { get; set; }
    }
}
