//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class vehicle_navigationEntities : DbContext
    {
        public vehicle_navigationEntities()
            : base("name=vehicle_navigationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ride_detail> ride_detail { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
    
        public virtual ObjectResult<GetNearestDrivers_Result> GetNearestDrivers(Nullable<decimal> orig_lat, Nullable<decimal> orig_long, Nullable<int> bounding_distance)
        {
            var orig_latParameter = orig_lat.HasValue ?
                new ObjectParameter("orig_lat", orig_lat) :
                new ObjectParameter("orig_lat", typeof(decimal));
    
            var orig_longParameter = orig_long.HasValue ?
                new ObjectParameter("orig_long", orig_long) :
                new ObjectParameter("orig_long", typeof(decimal));
    
            var bounding_distanceParameter = bounding_distance.HasValue ?
                new ObjectParameter("bounding_distance", bounding_distance) :
                new ObjectParameter("bounding_distance", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNearestDrivers_Result>("GetNearestDrivers", orig_latParameter, orig_longParameter, bounding_distanceParameter);
        }
    }
}
